- name: Demo on Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL from play
      ansible.builtin.debug:
        msg: URL = {{ URL }}
        ##msg: "{{ URL }} is the URL"

- name: Demo on file variables
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print URL from file
      ansible.builtin.debug:
        msg: URL = {{URL}}

## variables can be accessed as, spaces are not mandatory
# {{ var_name }} or {{var_name}}

- name: Task level Variables
  hosts: all
  tasks:
    - name: Print URL from task
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com

- name: Variables from Inventory
  hosts: all
  tasks:
    - name: Print URL from inventory
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: print Fact
  hosts: all
  tasks:
    - ansible.builtin.debug:
        msg: Hostname = {{ ansible_hostname }}