- name: Demo on Conditions
  hosts: localhost
  vars:
    a: 5
    bool_val: true
  tasks:
    - name: String Check or String Comparison
      debug:
        msg: Hello CentOS
      when: ansible_distribution == "CentOS"

    - name: Number Check or Number Comparison
      debug:
        msg: "{{a}} is greater than 1"
      when: a > 1

    - name: Run Task if bool_val is true
      debug:
        msg: Yes True
      when: bool_val | bool