- name: Demo on Conditions
  hosts: localhost
  vars:
    a: 5
  tasks:
    - name: String Check or String Comparison
      debug:
        msg: Hello CentOS
      when: ansible_distribution == "CentOS"

    - name: Number Check or Number Comparison
      debug:
        msg: "{{a}} is greater than 1"
      when: a > 1