- name: Run Shell Command
  ansible.builtin.shell: uptime
  register: out

- name: Print uptime Output
  ansible.builtin.debug:
    msg: "{{out.stdout}}"

- name: Print variable URL
  ansible.builtin.debug:
    msg: URL = {{ URL }}